// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('c:/Users/Dhison/Documents/GitHub/mehdi-gang/node_modules/react');
var { Component } = React;
var ReactNative = require('c:/Users/Dhison/Documents/GitHub/mehdi-gang/node_modules/react-native');
var { AppRegistry } = ReactNative;
var entryPoint = require('c:/Users/Dhison/Documents/GitHub/mehdi-gang/index.js');
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('gym-progression', appParameters);
});